package test;
import org.junit.Test;

import libraries.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'bluemlj' at '11/14/16 11:20 PM' with Gradle 3.0
 *
 * @author bluemlj, @date 11/14/16 11:20 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
